language: node_js
node_js:
  - 12
notifications:
  email: false
branches:
  only:
    - master
cache: yarn
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
install:
  - yarn
script:
  - yarn lint
  - yarn test
after_success:
  - yarn build
  - sudo sh deploy-dosc.sh